### ISSUE TITLE
How to remove the link in the folder and make it black?

### ISSUE THREAD

**Issue by sunghyunjeonme** [cflynn07/github-action-til-autoformat-readme#7]
First of all, thank you for making a good application ! 
In README.md, each folder name has a link tag, so it is displayed in blue. How do I change this part to black? I tried removing the link of the menu in README.md, but it was restored to its original state.

**Comment by cflynn07** [comment]
Hi @sunghyunjeonme sorry for the slow reply and you're welcome!
I'm not seeing the issue you're describing, could you share a screenshot?
<img width="923" alt="Screen Shot 2021-08-09 at 10 02 49 AM" src="https://user-images.githubusercontent.com/467885/128656342-a842af1f-d5a0-4e58-923e-4d4e83dfd952.png">

**Comment by isGeekCode** [comment]
혹시 해당 파일에 들어갔을떄, 첫줄에 공백일 경우 빈칸일 수 있습니다!!
