### ISSUE TITLE
tok anchor must change lowercased

### ISSUE THREAD

**Issue by isGeekCode** [cflynn07/github-action-til-autoformat-readme#9]
First of all, I would like to say thank you for contributing such a convenient tool.

I just want to make a request.

When a folder name is automatically created as a category section, an anchor is created in capital letters, preventing the toc function from being correctly linked.

So

the parts that are automatically created in the category should be processed as lower cased in a batch.

<img width="479" alt="스크린샷 2023-07-14 오전 10 06 04" src="https://github.com/cflynn07/github-action-til-autoformat-readme/assets/76529148/6f2761ba-067c-4946-be50-98a40097f384">

When I wrote Anchore in lowercase like the image below, I confirmed that it moves normally when I click on that part.

<img width="560" alt="스크린샷 2023-07-14 오전 10 12 01" src="https://github.com/cflynn07/github-action-til-autoformat-readme/assets/76529148/039171b1-04a5-42c0-8c0c-d068d4bc9e14">

**Comment by cflynn07** [comment]
Hi there, this should be fixed for you in release `1.2.1`

**Comment by cflynn07** [comment]
Actually use release 1.2.3
Fixed a few more bugs

**Comment by cflynn07** [comment]
Actually go with 1.2.4, fixed some bugs ;)
